#!/usr/bin/env python
# coding=utf-8

import sys

from AreteSlave.modules.Poker import Poker

if __name__ == "__main__":
    if len(sys.argv) == 4:
        test_id = sys.argv[1]
        poke_name = sys.argv[2]
        port = sys.argv[3]
        poker = Poker()
        poker.poke(test_id, poke_name, int(port))
    else:
        print 'Poke FAILED'
        exit(1)

