#!/usr/bin/env python

top = '.'
build = 'build'

def set_options(opt):
    opt.tool_options('compiler_cxx')


def configure(conf):
    conf.check_tool('compiler_cxx')

    conf.check(header_name='boost/version.hpp', uselib='BOOST', msg="Checking for Boost")
    conf.env.LIB_BOOST += ['boost_date_time']

    conf.check(header_name='Poco/Poco.h', uselib='POCO', msg="Checking for Poco")
    conf.env.LIB_POCO  += ['PocoNet', 'PocoXML']


def build(bld):
    bld(
        features = 'cxx cprogram',
        source   = 'configuration.cc main.cc',
        target   = 'controller',
        uselib     = ['POCO', 'BOOST'])
