srcdir='.'
blddir='output'
 
def configure(conf):
    conf.check_tool('tex')
    conf.find_program('pygmentize')
    conf.find_program('dia')
    conf.env.PDFLATEXFLAGS = ['-shell-escape']

def build(bld):

    def dia(src, tgt, layers=None):
        ls = ''
        if layers:
            ls = ' --show-layers=%s' % layers

        return bld(source=src, target=tgt,
            rule='dia ${SRC}' + ls + ' --export=${TGT}')

    dia('diagrams/konfiguracja-model-lab-mapping.dia',
        'diagrams/konfiguracja-model.eps',
        'model')

    dia('diagrams/konfiguracja-model-lab-mapping.dia',
        'diagrams/konfiguracja-laboratory.eps',
        'laboratory')

    dia('diagrams/konfiguracja-model-lab-mapping.dia',
        'diagrams/konfiguracja-mapping.eps',
        'model,laboratory,mapping')

    dia('diagrams/reference-config.dia',
        'diagrams/reference-config-model.eps',
        'model')

    dia('diagrams/reference-config.dia',
        'diagrams/reference-config-laboratory.eps',
        'laboratory')

    dia('diagrams/reference-config.dia',
        'diagrams/reference-config-schedule.eps',
        'schedule')

    bld.add_group()

    bld(features='tex', source='00-praca-magisterska.tex', prompt=0)
    bld(features='tex', source='01-przedmowa.tex', prompt=0)
    bld(features='tex', source='02-wprowadzenie.tex', prompt=0)
    bld(features='tex', source='konfiguracja.tex', prompt=0)

# vim: ft=python
